fix diff message

diff --git a/.buildkite/diff b/.buildkite/diff
--- a/.buildkite/diff
+++ b/.buildkite/diff
@@ -1,8 +1,10 @@
 #!/bin/bash
 
+[ $# -lt 1 ] && { echo "argument is missing."; exit 1; }
+
 COMMIT=$1
 
 BRANCH_POINT_COMMIT=$(git merge-base master $COMMIT)
 
-echo "Running diff between: $COMMIT - $BRANCH_POINT_COMMIT"
+echo "diff between $COMMIT and $BRANCH_POINT_COMMIT"
 git --no-pager diff --name-only $COMMIT..$BRANCH_POINT_COMMIT
